version: '3.7'

services:
  ibeacon-devices:
    container_name: ibeacon-devices
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: ibeacon-devices:latest
    volumes:
      - ./app:/application